language: node_js
node_js:
  - node
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -f schema.sql -U postgres
after_success:
  - npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: gRVWyQVqek7+lynzvyX5+y2weye3iKPFI3AZaeGRWyCxIHiG25TA9Eypjs/QS/VoMxhkuRfqsjRIerxtf82bXtJlt2AD2rZRtoi4SaMfKo9tcl9zSYhZIqHaSRFYq5McAfxQx2Sm+uuBA3X5MLNbUCVeyzjeAOkCEradMeeUdQY3+WrxS3mwhkJ7jbtxcszUCjrl17IKbMBN5OFs6CaMcFohNtGNJiMGRoSJhv/GST4Je+AuIOy3FtfkWT7B/SRxm24vRrC7TzSr9LO0WImwvIqBUxwDAYfvfv8DBsNj2gnyeF6AYVyQmaA/zkqspdHayvUfzwFiEcGehWxWWfMpAE/AnZy7pnLttNPHBt0YqjdO+KLAX4SczFjhzNhuERqERgqWB1+SUZZRYGs0UD3a1B+f3quoxeWdW3zwpnldsfNh0TnCskBZRcVh8jRtu5oHIskG4vy3hZsMDDTgnKTMS8U4H0JSJAVYwXZPrkpJ9oG69AXtXujXqPsWsB289fcu95lwGFL3sw+sEV4qBYOC1oSAIxmvH6RlD+326Lip29p+w1NIj5/bskN6rL8przggeVUVUyAFrSUjuO7lw/qPTaRWW0DDbY6ILVEE6LBBqk/msdTl1tMMra9Goto/tK9qgX1gqhHUIcbm8WteM50QDFcL58sB3+ZvqjKiGjwMZ4w=
