language: node_js
node_js:
- node
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- psql -f schema.sql -U postgres
after_success:
- npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: bB7kdkp/mM3Bs2Ij3Q3fyf+/RskA4bpI+kgpaBw+pLEtzVbzpzqJVpUwmbe2uy1rpuIe6rXYNYvqMQ+yzD2L49djR8A+q4PDPbEW7R5k8onUUOY2SzOh6ml6f4fCa96Y/hd627dp09R6kjEkNDeSvDWE/0CTX8ndABChZOJycSGDxNXCqq/qNjQjKftWksXO/9MBRurjA44twmh1YbxyWPrb1nt71sKquZGTseonTQRZfZFNnMqpYwa2ALy8R2V2zhy+PkynJOzXMHbofxfQ+DPMqlJ6LqgIRorSMS7JewaMcLbew45m1oomTUAETItYCop+WfpsWME+4O9xHmv68Vft9Lr4jxvjgTHI4o2T230IvFHghS06hKK8y57lo+tZ18y2HBiCbd3cn23auX9PMGCkwJUolUnqdGTC5NPHdHo+J4F3aJElRVI4ds8cbVAxeYZVjRKZALU6wMvxTq379B0lyzhvSB7Cr/mGYbD70bFF+hqX6DV49SFAmzsI0+6ZkIHkzNDdU8Kgyb2slGg7T/S5RlPiCm9fMTdZplj6NWPLGUMK7YAjTkkfNNRab453eqqzJczM1kXfiknp4V9Rxq50pRaKMstXapbr0/U2M5BZDfGTGLJvkOdE+EYIQhg/Bdb7rZKrLlW6JFl8L3JAPS2k0z08aVxiIiQvDzEMnyI=
